apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-service

generatorOptions: {}

secretGenerator:
- envs:
  - secret.env
  name: api-service

configMapGenerator:
- envs:
  - configmap.env
  name: api-service

helmCharts:
- name: hybiot-chart
  namespace: poc-develop
  releaseName: api-service
  repo: https://<registry>/helm-charts
  valuesFile: values.yaml
  version: 1.0.0

images:
- name: container-image
  newName: <registry>/services/python-app/backend/api-service
  newTag: v1.0.0
- name: init-container-image
  newName: <registry>/services/python-app/backend/api-service
  newTag: v1.0.0
