version: '3.8'
services:
  api-service:
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=DEV
    ports:
      - "8080:5000"
    depends_on:
      - redis
    command: gunicorn --bind 0.0.0.0:5000 app:app

  worker-service:
    build:
      context: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.celery worker

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

